# Site Information
site_name: Bjartur's Fab Academy Journey 
site_url: https://fab-lab-bjartur.tech/
repo_url: https://github.com/BjarturLeoHlynsson/fab-academy-site
repo_name: "Site Repo"

# Theme Configuration
theme:
  name: material
  
  # Branding
  logo: images/Logo/FabLabLogo.svg
  favicon: images/Logo/FabLabLogo.svg
  icon:
    repo: simple/github

  # Typography
  font:
    text: Roboto 
    code: Roboto Mono  

  # UI Features
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top

  # Color Schemes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle: 
        icon: material/lightbulb
        name: Switch to dark mode
      primary: black
      accent: red
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: black 
      accent: red 

# Markdown Processing
markdown_extensions:
  # Code Features
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.keys

  # Content Features
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html

  # Special Features
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Additional Features
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BjarturLeoHlynsson
      name: Github

plugins:
  - search
  - tags

nav:
  - Home: index.md
  - About:
    - Bio: about-me/bio.md
    - Student Agreement: about-me/agreement.md
  - Pre Fab:
    - 0. Overview: pre-fab/overview.md
    - 1. Website Making: pre-fab/week01.md
    - 2. Electronics Design and Production: pre-fab/week02.md
    - 3. Computer-Controlled Machining: pre-fab/week03.md
    - 4. Final Project: pre-fab/week04.md
    - 5. Computer-Aided Design: pre-fab/week05.md
  - Assignments:
    - 0. Overview: assignments/overview.md
    - 1. Principles and Practices: assignments/week01.md
    - 2. Computer-Aided Design: assignments/week02.md
    - 3. Computer-Controlled Cutting: assignments/week03.md
    - 4. Embedded Programming: assignments/week04.md
    - 5. 3D Scanning and Printing: assignments/week05.md
    - 6. Electronics Design: assignments/week06.md
    - 7. Computer-Controlled Machining: assignments/week07.md
    - 8. Electronics Production: assignments/week08.md
    - 9. Output Devices: assignments/week09.md
    - 10. Machine Week: assignments/week10.md
    - 11. Input Devices: assignments/week11.md
    - 12. Molding and Casting: assignments/week12.md
    - 13. Networking and Communications: assignments/week13.md
    - 14. Interface and Application Programming: assignments/week14.md
    - 15. Wild Card Week: assignments/week15.md
    - 16. Applications and Implications: assignments/week16.md
    - 17. Invention, Intellectual Property and Business Models: assignments/week17.md
    - 18-20. Project Development: assignments/week18.md
  - Final Project:
    - Overview: final-project/overview.md
