site_name: Bjartur's Fab Academy Journey

repo_name: Github Repository
repo_url: https://github.com/BjarturLeoHlynsson/fab-academy-test-site


theme:

  name: material
  
  logo: images/FabLabLogo.svg
  favicon: images/FabLabLogo.svg
  icon:
    repo: simple/github

  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: red

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: red
      favicon: images/FabLabLogo.svg